language: node_js
node_js:
  - 0.6
before_install:
 - sudo apt-get install sshfs
 - ssh-keygen -t rsa -f ~/.ssh/id_rsa -P ""
 - touch ~/.ssh/authorized_keys
 - cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys